import { createContext, useContext, useState, useEffect, type ReactNode } from "react";

export const LANGUAGES = [
  { code: "en", label: "English", flag: "🇬🇧", dir: "ltr" },
  { code: "fr", label: "Français", flag: "🇫🇷", dir: "ltr" },
  { code: "ru", label: "Русский", flag: "🇷🇺", dir: "ltr" },
  { code: "ro", label: "Română", flag: "🇷🇴", dir: "ltr" },
  { code: "ar", label: "العربية", flag: "🇸🇦", dir: "rtl" },
] as const;

export type LangCode = (typeof LANGUAGES)[number]["code"];

const UI_TRANSLATIONS: Record<LangCode, Record<string, string>> = {
  en: {
    yachts: "Yachts",
    cars: "Cars",
    about_us: "About Us",
    contact: "Contact",
    back_to_home: "Back to Home",
    currency: "Currency",
    per_day: "/ day",
    on_request: "On Request",
    call: "Call",
    whatsapp: "WhatsApp",
    first_name: "First Name",
    last_name: "Last Name",
    email: "Email",
    phone: "Phone",
    interest: "Asset of Interest",
    select_category: "Select Category...",
    yacht_charter: "Superyacht Charter",
    car_rental: "Hypercar Rental",
    combined: "Combined Experience",
    off_market: "Off-Market Request",
    request_details: "Request Details",
    request_placeholder: "Dates, location, special requirements...",
    submit_request: "Submit Private Request",
    processing: "Processing...",
    request_received: "Request Received",
    request_success: "Your form has been submitted. Our team will contact you as soon as possible.",
    request_error: "Failed to submit request. Please try again or contact us directly.",
    error: "Error",
    rights_reserved: "All rights reserved.",
    contact_us: "Contact Us",
    featured: "Featured",
    view_collection: "View Collection",
    view_full_collection: "View Full Collection",
    view_details: "View Details",
    full_description: "Full Description",
    specifications: "Specifications",
    gallery: "Gallery",
    request_this: "Request This",
    category_label: "Category",
    instagram: "Instagram",
    linkedin: "LinkedIn",
    charter_rate: "Charter Rate",
    concierge_response: "Our concierge will respond within 2 hours",
    not_found: "Not Found",
    listing_not_found: "This listing could not be found.",
    back_to_catalog: "Back to",
    interested_in: "Hi, I'm interested in",
    rates_unavailable: "rates unavailable",
    direct_contact: "Direct Contact",
    dedicated_concierge: "Dedicated Personal Concierge",
    worldwide_delivery: "Worldwide Delivery & Mooring",
    absolute_privacy: "Absolute Privacy Guaranteed",
    collections: "Collections",
    company: "Company",
    concierge: "Concierge",
    spec_engine: "Engine",
    spec_power: "Power (HP)",
    spec_torque: "Torque",
    spec_acceleration: "0–100 km/h",
    spec_top_speed: "Top Speed",
    spec_transmission: "Transmission",
    spec_drivetrain: "Drivetrain",
    spec_seats: "Seats",
    spec_fuel_type: "Fuel Type",
    spec_year: "Year",
    spec_km_included: "Kilometers Included",
    spec_extra_price_km: "Extra Price per km",
    spec_deposit: "Deposit",
    booking_total_amount: "Total Amount",
    booking_vat_percent: "VAT (%)",
    booking_agent_commission: "Agent Commission (%)",
    booking_contract_signed: "Contract Signed",
    spec_price_three_days: "Price / 3 Days",
    spec_price_month: "Price / Month",
    spec_length: "Length",
    spec_beam: "Beam",
    spec_draft: "Draft",
    spec_cabins: "Cabins",
    spec_guests: "Max Guests",
    spec_crew: "Crew",
    spec_cruising_speed: "Cruising Speed",
    spec_max_speed: "Max Speed",
    spec_fuel_capacity: "Fuel Capacity",
    spec_water_capacity: "Water Capacity",
    spec_year_built: "Year Built",
    spec_builder: "Builder / Shipyard",
    spec_type: "Type",
    spec_passengers: "Passengers",
    metric: "Metric",
    imperial: "Imperial",
    download_proposal: "Download Proposal",
    generating: "Generating…",
    proposal_error: "Failed to generate the proposal PDF. Please try again.",
    our_location: "Our Location",
  },
  fr: {
    yachts: "Yachts",
    cars: "Voitures",
    about_us: "À Propos",
    contact: "Contact",
    back_to_home: "Retour à l'accueil",
    currency: "Devise",
    per_day: "/ jour",
    on_request: "Sur Demande",
    call: "Appeler",
    whatsapp: "WhatsApp",
    first_name: "Prénom",
    last_name: "Nom",
    email: "E-mail",
    phone: "Téléphone",
    interest: "Intérêt",
    select_category: "Sélectionnez une catégorie...",
    yacht_charter: "Charter Superyacht",
    car_rental: "Location Hypercar",
    combined: "Expérience Combinée",
    off_market: "Demande Hors Marché",
    request_details: "Détails de la Demande",
    request_placeholder: "Dates, lieu, exigences particulières...",
    submit_request: "Envoyer la Demande Privée",
    processing: "Traitement...",
    request_received: "Demande Reçue",
    request_success: "Un concierge vous contactera sous peu pour finaliser votre expérience sur mesure.",
    request_error: "Échec de l'envoi de la demande. Veuillez réessayer ou nous contacter directement.",
    error: "Erreur",
    rights_reserved: "Tous droits réservés.",
    contact_us: "Contactez-Nous",
    featured: "En Vedette",
    view_collection: "Voir la Collection",
    view_full_collection: "Voir la Collection Complète",
    view_details: "Voir les Détails",
    full_description: "Description Complète",
    specifications: "Spécifications",
    gallery: "Galerie",
    request_this: "Demander",
    category_label: "Catégorie",
    instagram: "Instagram",
    linkedin: "LinkedIn",
    charter_rate: "Tarif de Location",
    concierge_response: "Notre conciergerie vous répondra dans les 2 heures",
    not_found: "Non Trouvé",
    listing_not_found: "Cette annonce est introuvable.",
    back_to_catalog: "Retour aux",
    interested_in: "Bonjour, je suis intéressé(e) par",
    rates_unavailable: "taux indisponibles",
    direct_contact: "Contact Direct",
    dedicated_concierge: "Concierge Personnel Dédié",
    worldwide_delivery: "Livraison & Amarrage Mondial",
    absolute_privacy: "Confidentialité Absolue Garantie",
    collections: "Collections",
    company: "Entreprise",
    concierge: "Conciergerie",
    spec_engine: "Moteur",
    spec_power: "Puissance (CV)",
    spec_torque: "Couple",
    spec_acceleration: "0–100 km/h",
    spec_top_speed: "Vitesse Max",
    spec_transmission: "Transmission",
    spec_drivetrain: "Transmission",
    spec_seats: "Places",
    spec_fuel_type: "Carburant",
    spec_year: "Année",
    spec_km_included: "Kilomètres Inclus",
    spec_extra_price_km: "Prix Extra par km",
    spec_deposit: "Dépôt",
    booking_total_amount: "Montant Total",
    booking_vat_percent: "TVA (%)",
    booking_agent_commission: "Commission Agent (%)",
    booking_contract_signed: "Contrat Signé",
    spec_price_three_days: "Prix / 3 Jours",
    spec_price_month: "Prix / Mois",
    spec_length: "Longueur",
    spec_beam: "Largeur",
    spec_draft: "Tirant d'eau",
    spec_cabins: "Cabines",
    spec_guests: "Invités Max",
    spec_crew: "Équipage",
    spec_cruising_speed: "Vitesse de Croisière",
    spec_max_speed: "Vitesse Max",
    spec_fuel_capacity: "Capacité Carburant",
    spec_water_capacity: "Capacité Eau",
    spec_year_built: "Année de Construction",
    spec_builder: "Constructeur / Chantier",
    spec_type: "Type",
    spec_passengers: "Passagers",
    metric: "Métrique",
    imperial: "Impérial",
    download_proposal: "Télécharger le Dossier",
    generating: "Génération…",
    proposal_error: "Échec de la génération du PDF. Veuillez réessayer.",
    our_location: "Notre Adresse",
  },
  ru: {
    yachts: "Яхты",
    cars: "Автомобили",
    about_us: "О Нас",
    contact: "Контакт",
    back_to_home: "Вернуться на главную",
    currency: "Валюта",
    per_day: "/ день",
    on_request: "По Запросу",
    call: "Позвонить",
    whatsapp: "WhatsApp",
    first_name: "Имя",
    last_name: "Фамилия",
    email: "Эл. почта",
    phone: "Телефон",
    interest: "Интересующий актив",
    select_category: "Выберите категорию...",
    yacht_charter: "Чартер Суперяхты",
    car_rental: "Аренда Гиперкара",
    combined: "Комплексный Опыт",
    off_market: "Закрытый Запрос",
    request_details: "Детали Запроса",
    request_placeholder: "Даты, локация, особые требования...",
    submit_request: "Отправить Частный Запрос",
    processing: "Обработка...",
    request_received: "Запрос Получен",
    request_success: "Консьерж свяжется с вами в ближайшее время для оформления вашего эксклюзивного опыта.",
    request_error: "Не удалось отправить запрос. Пожалуйста, попробуйте снова или свяжитесь с нами напрямую.",
    error: "Ошибка",
    rights_reserved: "Все права защищены.",
    contact_us: "Свяжитесь с Нами",
    featured: "Избранное",
    view_collection: "Смотреть Коллекцию",
    view_full_collection: "Полная Коллекция",
    full_description: "Полное Описание",
    specifications: "Характеристики",
    gallery: "Галерея",
    request_this: "Запросить",
    category_label: "Категория",
    instagram: "Instagram",
    linkedin: "LinkedIn",
    charter_rate: "Стоимость Аренды",
    concierge_response: "Наш консьерж ответит в течение 2 часов",
    not_found: "Не Найдено",
    listing_not_found: "Это объявление не найдено.",
    back_to_catalog: "Назад к",
    interested_in: "Здравствуйте, меня интересует",
    rates_unavailable: "курсы недоступны",
    direct_contact: "Прямой Контакт",
    dedicated_concierge: "Персональный Консьерж",
    worldwide_delivery: "Доставка и Швартовка по Всему Миру",
    absolute_privacy: "Абсолютная Конфиденциальность",
    collections: "Коллекции",
    company: "Компания",
    concierge: "Консьерж",
    view_details: "Подробнее",
    spec_engine: "Двигатель",
    spec_power: "Мощность (л.с.)",
    spec_torque: "Крутящий момент",
    spec_acceleration: "0–100 км/ч",
    spec_top_speed: "Макс. Скорость",
    spec_transmission: "Трансмиссия",
    spec_drivetrain: "Привод",
    spec_seats: "Места",
    spec_fuel_type: "Тип Топлива",
    spec_year: "Год",
    spec_km_included: "Километры Включены",
    spec_extra_price_km: "Доплата за км",
    spec_deposit: "Депозит",
    booking_total_amount: "Общая сумма",
    booking_vat_percent: "НДС (%)",
    booking_agent_commission: "Комиссия агента (%)",
    booking_contract_signed: "Договор подписан",
    spec_price_three_days: "Цена / 3 дня",
    spec_price_month: "Цена / месяц",
    spec_length: "Длина",
    spec_beam: "Ширина",
    spec_draft: "Осадка",
    spec_cabins: "Каюты",
    spec_guests: "Макс. Гостей",
    spec_crew: "Экипаж",
    spec_cruising_speed: "Крейсерская Скорость",
    spec_max_speed: "Макс. Скорость",
    spec_fuel_capacity: "Ёмкость Топлива",
    spec_water_capacity: "Ёмкость Воды",
    spec_year_built: "Год Постройки",
    spec_builder: "Верфь / Строитель",
    spec_type: "Тип",
    spec_passengers: "Пассажиры",
    metric: "Метрическая",
    imperial: "Имперская",
    download_proposal: "Скачать Предложение",
    generating: "Создание…",
    proposal_error: "Не удалось создать PDF. Пожалуйста, попробуйте снова.",
    our_location: "Наш Офис",
  },
  ro: {
    yachts: "Iahturi",
    cars: "Mașini",
    about_us: "Despre Noi",
    contact: "Contact",
    back_to_home: "Înapoi la pagina principală",
    currency: "Monedă",
    per_day: "/ zi",
    on_request: "La Cerere",
    call: "Sună",
    whatsapp: "WhatsApp",
    first_name: "Prenume",
    last_name: "Nume",
    email: "E-mail",
    phone: "Telefon",
    interest: "Interes",
    select_category: "Selectați categoria...",
    yacht_charter: "Charter Superyacht",
    car_rental: "Închiriere Hypercar",
    combined: "Experiență Combinată",
    off_market: "Cerere Off-Market",
    request_details: "Detalii Cerere",
    request_placeholder: "Date, locație, cerințe speciale...",
    submit_request: "Trimiteți Cererea Privată",
    processing: "Se procesează...",
    request_received: "Cerere Primită",
    request_success: "Un concierge vă va contacta în curând pentru a finaliza experiența dvs. personalizată.",
    request_error: "Nu s-a putut trimite cererea. Încercați din nou sau contactați-ne direct.",
    error: "Eroare",
    rights_reserved: "Toate drepturile rezervate.",
    contact_us: "Contactați-ne",
    featured: "Recomandate",
    view_collection: "Vezi Colecția",
    view_full_collection: "Colecția Completă",
    full_description: "Descriere Completă",
    specifications: "Specificații",
    gallery: "Galerie",
    request_this: "Solicită",
    category_label: "Categorie",
    instagram: "Instagram",
    linkedin: "LinkedIn",
    charter_rate: "Tariful de Închiriere",
    concierge_response: "Concierge-ul nostru va răspunde în 2 ore",
    not_found: "Nu a fost găsit",
    listing_not_found: "Acest anunț nu a putut fi găsit.",
    back_to_catalog: "Înapoi la",
    interested_in: "Bună, sunt interesat(ă) de",
    rates_unavailable: "cursuri indisponibile",
    direct_contact: "Contact Direct",
    dedicated_concierge: "Concierge Personal Dedicat",
    worldwide_delivery: "Livrare & Amarare la Nivel Mondial",
    absolute_privacy: "Confidențialitate Absolută Garantată",
    collections: "Colecții",
    company: "Companie",
    concierge: "Concierge",
    view_details: "Vezi Detalii",
    spec_engine: "Motor",
    spec_power: "Putere (CP)",
    spec_torque: "Cuplu",
    spec_acceleration: "0–100 km/h",
    spec_top_speed: "Viteză Maximă",
    spec_transmission: "Transmisie",
    spec_drivetrain: "Tracțiune",
    spec_seats: "Locuri",
    spec_fuel_type: "Tip Combustibil",
    spec_year: "An",
    spec_km_included: "Kilometri Incluși",
    spec_extra_price_km: "Preț Extra per km",
    spec_deposit: "Depozit",
    booking_total_amount: "Suma Totală",
    booking_vat_percent: "TVA (%)",
    booking_agent_commission: "Comision Agent (%)",
    booking_contract_signed: "Contract Semnat",
    spec_price_three_days: "Preț / 3 Zile",
    spec_price_month: "Preț / Lună",
    spec_length: "Lungime",
    spec_beam: "Lățime",
    spec_draft: "Pescaj",
    spec_cabins: "Cabine",
    spec_guests: "Oaspeți Max",
    spec_crew: "Echipaj",
    spec_cruising_speed: "Viteză de Croazieră",
    spec_max_speed: "Viteză Maximă",
    spec_fuel_capacity: "Capacitate Combustibil",
    spec_water_capacity: "Capacitate Apă",
    spec_year_built: "Anul Construcției",
    spec_builder: "Constructor / Șantier",
    spec_type: "Tip",
    spec_passengers: "Pasageri",
    metric: "Metric",
    imperial: "Imperial",
    download_proposal: "Descarcă Propunerea",
    generating: "Se generează…",
    proposal_error: "Eroare la generarea PDF-ului. Încercați din nou.",
    our_location: "Locația Noastră",
  },
  ar: {
    yachts: "يخوت",
    cars: "سيارات",
    about_us: "من نحن",
    contact: "اتصل بنا",
    back_to_home: "العودة إلى الرئيسية",
    currency: "العملة",
    per_day: "/ يوم",
    on_request: "عند الطلب",
    call: "اتصال",
    whatsapp: "واتساب",
    first_name: "الاسم الأول",
    last_name: "اسم العائلة",
    email: "البريد الإلكتروني",
    phone: "الهاتف",
    interest: "الاهتمام",
    select_category: "اختر الفئة...",
    yacht_charter: "استئجار يخت فاخر",
    car_rental: "تأجير سيارات خارقة",
    combined: "تجربة مشتركة",
    off_market: "طلب خاص",
    request_details: "تفاصيل الطلب",
    request_placeholder: "التواريخ، الموقع، المتطلبات الخاصة...",
    submit_request: "إرسال الطلب الخاص",
    processing: "جاري المعالجة...",
    request_received: "تم استلام الطلب",
    request_success: "سيتواصل معك مسؤول الخدمة قريباً لإتمام تجربتك المميزة.",
    request_error: "فشل إرسال الطلب. يرجى المحاولة مرة أخرى أو الاتصال بنا مباشرة.",
    error: "خطأ",
    rights_reserved: "جميع الحقوق محفوظة.",
    contact_us: "اتصل بنا",
    featured: "مميز",
    view_collection: "عرض المجموعة",
    view_full_collection: "المجموعة الكاملة",
    full_description: "الوصف الكامل",
    specifications: "المواصفات",
    gallery: "معرض الصور",
    request_this: "اطلب هذا",
    category_label: "الفئة",
    instagram: "إنستغرام",
    linkedin: "لينكدإن",
    charter_rate: "سعر الإيجار",
    concierge_response: "سيرد عليكم فريق الكونسيرج خلال ساعتين",
    not_found: "غير موجود",
    listing_not_found: "لم يتم العثور على هذا الإعلان.",
    back_to_catalog: "العودة إلى",
    interested_in: "مرحباً، أنا مهتم بـ",
    rates_unavailable: "الأسعار غير متوفرة",
    direct_contact: "اتصال مباشر",
    dedicated_concierge: "خدمة كونسيرج شخصية",
    worldwide_delivery: "التوصيل والرسو حول العالم",
    absolute_privacy: "خصوصية مطلقة مضمونة",
    collections: "المجموعات",
    company: "الشركة",
    concierge: "الكونسيرج",
    view_details: "عرض التفاصيل",
    spec_engine: "المحرك",
    spec_power: "القوة (حصان)",
    spec_torque: "عزم الدوران",
    spec_acceleration: "0–100 كم/س",
    spec_top_speed: "السرعة القصوى",
    spec_transmission: "ناقل الحركة",
    spec_drivetrain: "نظام الدفع",
    spec_seats: "المقاعد",
    spec_fuel_type: "نوع الوقود",
    spec_year: "السنة",
    spec_km_included: "الكيلومترات المشمولة",
    spec_extra_price_km: "سعر إضافي لكل كم",
    spec_deposit: "التأمين",
    booking_total_amount: "المبلغ الإجمالي",
    booking_vat_percent: "ضريبة القيمة المضافة (%)",
    booking_agent_commission: "عمولة الوكيل (%)",
    booking_contract_signed: "تم توقيع العقد",
    spec_price_three_days: "السعر / 3 أيام",
    spec_price_month: "السعر / الشهر",
    spec_length: "الطول",
    spec_beam: "العرض",
    spec_draft: "الغاطس",
    spec_cabins: "الكبائن",
    spec_guests: "أقصى عدد ضيوف",
    spec_crew: "الطاقم",
    spec_cruising_speed: "سرعة الإبحار",
    spec_max_speed: "السرعة القصوى",
    spec_fuel_capacity: "سعة الوقود",
    spec_water_capacity: "سعة المياه",
    spec_year_built: "سنة البناء",
    spec_builder: "الشركة المصنعة",
    spec_type: "النوع",
    spec_passengers: "الركاب",
    metric: "متري",
    imperial: "إمبراطوري",
    download_proposal: "تحميل العرض",
    generating: "جارٍ الإنشاء…",
    proposal_error: "فشل إنشاء ملف PDF. يرجى المحاولة مرة أخرى.",
    our_location: "موقعنا",
  },
};

interface LanguageContextType {
  lang: LangCode;
  setLang: (lang: LangCode) => void;
  t: (key: string) => string;
  dir: "ltr" | "rtl";
}

const LanguageContext = createContext<LanguageContextType>({
  lang: "en",
  setLang: () => {},
  t: (key: string) => key,
  dir: "ltr",
});

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<LangCode>(() => {
    const saved = localStorage.getItem("tyg_lang");
    return (saved && LANGUAGES.some(l => l.code === saved)) ? (saved as LangCode) : "en";
  });

  const setLang = (newLang: LangCode) => {
    setLangState(newLang);
    localStorage.setItem("tyg_lang", newLang);
  };

  const langInfo = LANGUAGES.find(l => l.code === lang)!;
  const dir = langInfo.dir as "ltr" | "rtl";

  useEffect(() => {
    document.documentElement.dir = dir;
    document.documentElement.lang = lang;
  }, [lang, dir]);

  const t = (key: string): string => {
    return UI_TRANSLATIONS[lang]?.[key] || UI_TRANSLATIONS.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t, dir }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
