ALTER TABLE contracts
  ADD COLUMN IF NOT EXISTS request_id VARCHAR(64) UNIQUE,
  ADD COLUMN IF NOT EXISTS snapshot JSONB,
  ADD COLUMN IF NOT EXISTS pdf_sha256 VARCHAR(64),
  ADD COLUMN IF NOT EXISTS pdf_base64 TEXT,
  ADD COLUMN IF NOT EXISTS template_version VARCHAR(30),
  ADD COLUMN IF NOT EXISTS issued_at TIMESTAMP;

ALTER TABLE contracts
  ALTER COLUMN total_amount TYPE NUMERIC(12,2) USING total_amount::NUMERIC,
  ALTER COLUMN deposit_amount TYPE NUMERIC(12,2) USING deposit_amount::NUMERIC,
  ALTER COLUMN extra_km_price TYPE NUMERIC(12,2) USING extra_km_price::NUMERIC;
